import {
  serialize as simpleSerialize,
  SerializeOptions as SimpleSerializeOptions,
  SerializeResult
} from 'simple-serialization';
import {possiblyAsync} from 'possibly-async';
import {isES2015Class} from 'core-helpers';

import type {ComponentSet} from './component';
import type {PropertyFilter, AttributeSelector} from './properties';
import {isComponentClassOrInstance} from './utilities';

export type SerializeOptions = SimpleSerializeOptions & {
  attributeSelector?: AttributeSelector;
  attributeFilter?: PropertyFilter;
  serializedComponents?: ComponentSet;
  componentDependencies?: ComponentSet;
  serializeFunctions?: boolean;
  returnComponentReferences?: boolean;
  ignoreEmptyComponents?: boolean;
  includeComponentTypes?: boolean;
  includeIsNewMarks?: boolean;
  includeReferencedComponents?: boolean;
  target?: number;
};

export function serialize<Value>(value: Value, options?: SerializeOptions): SerializeResult<Value>;
export function serialize(value: any, options: SerializeOptions = {}) {
  const {
    serializedComponents = new Set(),
    objectSerializer: originalObjectSerializer,
    functionSerializer: originalFunctionSerializer,
    serializeFunctions = false,
    ...otherOptions
  } = options;

  const objectSerializer = function (object: object): object | void {
    if (originalObjectSerializer !== undefined) {
      const serializedObject = originalObjectSerializer(object);

      if (serializedObject !== undefined) {
        return serializedObject;
      }
    }

    if (isComponentClassOrInstance(object)) {
      return object.serialize({...options, serializedComponents});
    }
  };

  let functionSerializer: SerializeOptions['functionSerializer'];

  if (serializeFunctions) {
    functionSerializer = function (func) {
      if (originalFunctionSerializer !== undefined) {
        const serializedFunction = originalFunctionSerializer(func);

        if (serializedFunction !== undefined) {
          return serializedFunction;
        }
      }

      if (isES2015Class(func)) {
        throw new Error('Cannot serialize a class');
      }

      const functionCode = serializeFunction(func);

      const serializedFunction = {__function: functionCode};

      return possiblyAsync(
        possiblyAsync.mapValues(func as any, (attributeValue) =>
          simpleSerialize(attributeValue, {...otherOptions, objectSerializer, functionSerializer})
        ),
        (serializedAttributes) => {
          Object.assign(serializedFunction, serializedAttributes);
          return serializedFunction;
        }
      );
    };
  }

  return simpleSerialize(value, {...otherOptions, objectSerializer, functionSerializer});
}

export function serializeFunction(func: Function) {
  let sourceCode = func.toString();

  // Clean functions generated by `new Function()`
  if (sourceCode.startsWith('function anonymous(\n)')) {
    sourceCode = 'function ()' + sourceCode.slice('function anonymous(\n)'.length);
  }

  return sourceCode;
}
