export const BACKEND_URL = process.env.BACKEND_URL;

export const FRONTEND_URL = process.env.FRONTEND_URL;

export const MONGODB_STORE_CONNECTION_STRING = process.env.MONGODB_STORE_CONNECTION_STRING;

export const MAILER_LITE_API_KEY = process.env.MAILER_LITE_API_KEY;

export const MAILER_LITE_NEWSLETTER_SUBSCRIPTIONS_GROUP_ID =
  process.env.MAILER_LITE_NEWSLETTER_SUBSCRIPTIONS_GROUP_ID;

export const JWT_SECRET = process.env.JWT_SECRET;
